services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcache:
    image: redis
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalogdb

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on: 
      - basketdb
      - distributedcache
    
  front:
    image: front
    build:
      context: /home/seif/Downloads/ecommerce-dashboard
      dockerfile: /home/seif/Downloads/ecommerce-dashboard/Dockerfile
    ports:
      - "6002:80"
      
volumes:
  postgres_catalog:
  postgres_basket: 


